Pussy time pussy clean pussy fresh
utendo/site pull request #1
Opened 2022-07-03 00:00 UTC by kevadesu

first of all, you could've written Follow our Twitter, would've been simpler right? Then, a card has no face. sure it can be ugly or beautiful, but is it a living thing? 💀 I suggest you remove the word "face". better right? good. it was nice doing business with you.

2022-07-03 00:31 UTC, kevadesu commented
Merge be when? 👀

2022-07-03 00:34 UTC, locness3 commented
Thank you for the pull request!

> you could've written Follow our Twitter

Better to say what to expect from the Twitter

> Then, a card has no face.

You might be right, maybe a more appropriate word would be "side". If you're going to change this, you could change the relevant markup and style as well. Btw this is unused code.

> but is it a living thing

Our projects are currently alive and that's a good thing \:)

> it was nice doing business with you.

Wouldn't say we're doing business, we're just having fun

2022-07-03 00:36 UTC, kevadesu commented
> Thank you for the pull request!
> 
> > you could've written Follow our Twitter
> 
> Better to say what to expect from the Twitter
> 
> > Then, a card has no face.
> 
> You might be right, maybe a more appropriate word would be "side". If you're going to change this, you could change the relevant markup and style as well. Btw this is unused code.
> 
> > but is it a living thing
> 
> Our projects are currently alive and that's a good thing \:)
> 
> > it was nice doing business with you.
> 
> Wouldn't say we're doing business, we're just having fun

The "doing business" part was just a joke

2022-07-03 00:39 UTC, locness3 commented
If you'd like to merge this, please :

- Revert the Twitter change
- change parts of markup and stylesheets that uses the word "face" to use "side"

2022-07-03 00:39 UTC, kevadesu commented
> If you'd like to merge this, please :
> 
> - Revert the Twitter change
> - change parts of markup and stylesheets that uses the word "face" to use "side"

Very well. One second

2022-07-03 00:42 UTC, kevadesu commented
done

2022-07-03 00:46 UTC, locness3 commented
I'm still seeing `face` classes in the HTML and in the relevant SCSS file. \:)

2022-07-03 00:46 UTC, kevadesu commented
> I'm still seeing `face` classes in the HTML and in the relevant SCSS file. :)

oops lemme fix

2022-07-03 00:50 UTC, kevadesu commented
done

2022-07-03 13:37 UTC, locness3 requested changes

2022-07-03 13:37 UTC, locness3 commented on assets/css/style.css
> +﻿body{color:#fff;background-color:#000;font-family:"Lato",sans-serif}img{max-width:100%;margin:1em 0}.container{max-width:800px;margin:0 auto}.main-header{margin:5em auto 5em auto;text-align:center}#
@kevadesu please read assets/css/README.txt

2022-09-20 22:17 UTC, locness3 commented
Please consider closing this pull request or making the requested changes

2022-10-02 17:12 UTC, kevadesu commented
yeah ok sure I'll close it

2022-10-02 17:12 UTC, closed without merging